version: "3.7"

services:
  db:
    container_name: ${PROJECT:-marketplace}_db
    image: postgres:12-alpine3.16
    environment:
      - POSTGRES_DB=${DB_NAME:-marketplace_dev}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-12wqasxz}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT:-5432}:5432'
    restart: always
    networks:
      - bridge
  redis:
    container_name: ${PROJECT:-marketplace}_redis
    restart: always
    image: 'redis:7'
    ports:
      - "${REDIS_PORT:-6379}:6379"
    env_file:
      - .env
    networks:
      - bridge
  django:
    &django
    container_name: ${PROJECT:-marketplace}_django
    image: ${PROJECT:-marketplace}-django:latest
    build: ./marketplace
    volumes:
      - ./marketplace:/marketplace
      - ./marketplace/static:/marketplace/static
      - ./marketplace/${LOGS_DIR:-logs}:/marketplace/${LOGS_DIR:-logs}
    ports:
      - '${DJANGO_PORT:-8000}:8000'
    env_file:
      - ./.env
    restart: always
    networks:
      - bridge
  celery:
    <<: *django
    container_name: ${PROJECT:-marketplace}_celery
    entrypoint: /marketplace/entrypoint-celery.sh
    ports:
      - '${CELERY_PORT}:6380'
    env_file:
      - .env
    depends_on:
      - django
      - redis
  payment_service:
    container_name: ${PROJECT:-marketplace}_payment_service
    image: ${PROJECT:-marketplace}-payment_service:latest
    build: ./payment_service
    volumes:
      - ./payment_service:/payment_service
    ports:
      - '${PAYMENT_API_PORT:-5000}:5000'
    env_file:
      - ./.env
    restart: always
    networks:
      - bridge

networks:
  bridge:
    driver: bridge

volumes:
  pgdata: